name: Firebase Korea
title: Firebase Korea Blog
email: mydamyda1032[at]]gmail.com
description: Firebase Blog for Korean User
baseurl: ""

url: "https://firebasekorea.io/"


# Social Network
github: https://github.com/FirebaseKorea
facebook: https://www.facebook.com/groups/671723382988386/

# disqus
disqus: # insert disqus or comment system

# Conversion
markdown:    redcarpet
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough", "highlight"]

kramdown:
  input: GFM
  hard_wrap: false

theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: /css/_sass

paginate: 5

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
- scope:
    path: "our_post"
    type: "posts"
  values:
    layout: "our_post"
    categories: "our_post"
- scope:
    path: "our_open_source"
    type: "posts"
  values:
    layout: "our_open_source"
    categories: "our_open_source"
- scope:
    path: "official_post"
    type: "posts"
  values:
    layout: "official_post"
    categories: "official_post"
- scope:
    path: "official_open_source"
    type: "posts"
  values:
    layout: "official_open_source"
    categories: "official_open_source"
- scope:
    path: "organizer"
    type: "posts"
  values:
    layout: "organizer"
    categories: "organizer"
