title: Firebase Korea Blog
email: mydamyda1032[at]]gmail.com
description: Firebase Korea Blog
baseurl: ""

url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Social Network
github: https://github.com/FirebaseKorea
facebook: https://www.facebook.com/groups/671723382988386/

# disqus
disqus: # insert disqus or comment system

# Build settings
kramdown:
  input: GFM
  hard_wrap: false

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: /css/_sass

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
- scope:
    path: "our_post"
    type: "posts"
  values:
    layout: "our_post"
    categories: "our_post"
- scope:
    path: "our_open_source"
    type: "posts"
  values:
    layout: "our_open_source"
    categories: "our_open_source"
- scope:
    path: "official_post"
    type: "posts"
  values:
    layout: "official_post"
    categories: "official_post"
- scope:
    path: "official_open_source"
    type: "posts"
  values:
    layout: "official_open_source"
    categories: "official_open_source"
- scope:
    path: "organizer"
    type: "posts"
  values:
    layout: "organizer"
    categories: "organizer"
